# Jekyll configuration for Gatekeeper documentation
title: Gatekeeper
description: A powerful HTTP middleware library for Go that provides comprehensive request filtering and protection capabilities
url: "https://your-username.github.io"
baseurl: "/gatekeeper"

# Theme configuration
remote_theme: pmarsceill/just-the-docs

# Color scheme (optional)
color_scheme: nil

# Search configuration
search_enabled: true
search:
  heading_level: 2
  previews: 3
  preview_words_before: 5
  preview_words_after: 10
  tokenizer_separator: /[\s/]+/
  rel_url: true

# Navigation structure
nav_sort: case_insensitive

# Enable or disable the site search
search_enabled: true

# Heading anchor links appear on hover over h1-h6 tags in page content
heading_anchors: true

# Aux links for the upper right navigation
aux_links:
  "Gatekeeper on GitHub":
    - "//github.com/your-username/gatekeeper"

# Makes Aux links open in a new tab. Default is false
aux_links_new_tab: false

# Sort order for navigation links
nav_sort: case_insensitive

# Footer content
footer_content: "Copyright &copy; 2024 Gatekeeper. Distributed by an <a href=\"https://github.com/your-username/gatekeeper/tree/main/LICENSE\">MIT license.</a>"

# Footer last edit timestamp
last_edit_timestamp: true
last_edit_time_format: "%b %e %Y at %I:%M %p"

# Footer "Edit this page on GitHub" link text
gh_edit_link: true
gh_edit_link_text: "Edit this page on GitHub"
gh_edit_repository: "https://github.com/your-username/gatekeeper"
gh_edit_branch: "main"
gh_edit_source: docs
gh_edit_view_mode: "tree"

# Build settings
markdown: kramdown
kramdown:
  syntax_highlighter: rouge
  syntax_highlighter_opts:
    block:
      line_numbers: false

plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-seo-tag

# Exclude from processing
exclude:
  - node_modules/
  - "*.gemspec"
  - "*.gem"
  - Gemfile
  - Gemfile.lock
  - package.json
  - package-lock.json
  - script/
  - LICENSE.txt
  - lib/
  - bin/
  - README.md
  - Rakefile

# Collections for organizing content
collections:
  guides:
    permalink: "/:collection/:name/"
    output: true
  reference:
    permalink: "/:collection/:name/"
    output: true
  examples:
    permalink: "/:collection/:name/"
    output: true
  tutorials:
    permalink: "/:collection/:name/"
    output: true

defaults:
  - scope:
      path: ""
      type: "pages"
    values:
      layout: "default"
  - scope:
      path: ""
      type: "guides"
    values:
      layout: "default"
      nav_order: 2
  - scope:
      path: ""
      type: "reference"
    values:
      layout: "default"
      nav_order: 3
  - scope:
      path: ""
      type: "examples"
    values:
      layout: "default"
      nav_order: 4
  - scope:
      path: ""
      type: "tutorials"
    values:
      layout: "default"
      nav_order: 5
