source "https://rubygems.org"

gem "github-pages", group: :jekyll_plugins
gem "just-the-docs"

# If you have any plugins, put them here!
group :jekyll_plugins do
  gem "jekyll-feed"
  gem "jekyll-sitemap"
  gem "jekyll-seo-tag"
end
